services:
  postgresql:
    image: postgres:13.9-alpine
    container_name: postgresql
    hostname: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insurance
      PGDATA: /data/postgres
    volumes:
      - "postgres-data:/data/insurance"

  insurance-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: insurance-service
    hostname: insurance-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      DATABASE_NAME: insurance
    depends_on:
      - postgresql

volumes:
  postgres-data:
    driver: local